# Generated by Django 6.0.5 on 2026-05-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_updated_at_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categry',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
