# Generated by Django 6.0.5 on 2026-05-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_categry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categry',
            new_name='category',
        ),
    ]
