# Generated by Django 6.0.5 on 2026-05-18 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_file_upload'),
    ]

    operations = [
        # 1단계: Category 모델 생성
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        # 2단계: 기존 category(VARCHAR NOT NULL → VARCHAR NULL)로 먼저 변경
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        # 3단계: 빈 문자열 값을 NULL로 정리
        migrations.RunSQL(
            "UPDATE blog_post SET category = NULL WHERE category = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 4단계: NULL이 된 VARCHAR → ForeignKey로 변경
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
